### PR TITLE
Deprecate charts

### PR DESCRIPTION
**Pull request by ghost**
# Description

Some charts have become irrelevant as we moved them to our terraform code.

# Related Issue

# Motivation and Context

# How Has This Been Tested?

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist

- [ ] I have followed the PR process as described [here](https://github.com/skyscrapers/documentation/blob/master/coding_guidelines/git.md#pull-requests)
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by duboisph — APPROVED** [review]
I'd just say "This chart is deprecated for Skyscrapers", the why is not really necessary? (and not 100% correct either)

**Comment by ghost** [comment]
@duboisph Using the same deprecation notice as used [before](https://github.com/skyscrapers/charts/commit/1b515918d617a52df0c76c67d59e68b678a8e367).

Do we want to keep it aligned?

**Comment by duboisph** [comment]
Imho no, but it's your call.

**Comment by ghost** [comment]
Okay, changed it accordingly.

**Pull request merged**
