### PR TITLE
Adjust severity for RDS alerts

### PR DESCRIPTION
**Pull request by simonrondelez**

### CODE REVIEW

**Review by iuriaranda — COMMENTED** [review]
not really sure if all these should be a warning. For example a low memory could have a critical impact on apps. Or replica lag could also be quite bad. No?

**Comment by simonrondelez** [comment]
> not really sure if all these should be a warning. For example a low memory could have a critical impact on apps. Or replica lag could also be quite bad. No?

For the memory alert: maybe. For the replica lag: thats why i changed it from warning to critical ;)

**Comment by iuriaranda** [comment]
> > not really sure if all these should be a warning. For example a low memory could have a critical impact on apps. Or replica lag could also be quite bad. No?
> 
> For the memory alert: maybe. For the replica lag: thats why i changed it from warning to critical ;)

True that. Well I'm ok with keeping the replica lag alert as a warning then.

**Comment by simonrondelez** [comment]
> > > not really sure if all these should be a warning. For example a low memory could have a critical impact on apps. Or replica lag could also be quite bad. No?
> > 
> > 
> > For the memory alert: maybe. For the replica lag: thats why i changed it from warning to critical ;)
> 
> True that. Well I'm ok with keeping the replica lag alert as a warning then.

You mean the memory alert right? :D

**Comment by iuriaranda** [comment]
ah damn, I misread your initial comment 😅 

yes, so keep the replica lag to critical 😛 
what about the memory alert? I believe that should be critical as well no? Or maybe add another alert with a lower threshold and set it to critical. For example:

`RDSFreeableMemoryLow` - warning - < 100Mb
`RDSFreeableMemoryVeryLow` - critical - < 1Mb

And also thinking about it, it might be a good idea to do the same for the CPU credits, adding a critical one for when the credit balance is 0 for more than 30 minutes?

**Comment by simonrondelez** [comment]
> ah damn, I misread your initial comment 😅
> 
> yes, so keep the replica lag to critical 😛
> what about the memory alert? I believe that should be critical as well no? Or maybe add another alert with a lower threshold and set it to critical. For example:
> 
> `RDSFreeableMemoryLow` - warning - < 100Mb
> `RDSFreeableMemoryVeryLow` - critical - < 1Mb
> 
> And also thinking about it, it might be a good idea to do the same for the CPU credits, adding a critical one for when the credit balance is 0 for more than 30 minutes?

Adjusted the memory alerts.

For the CPU credits: i really don't think we should be alerted for that. If its a critical RDS it shouldn't be a burstable type imo.

**Review by iuriaranda — APPROVED** [review]

**Pull request merged**
